# Generated by Django 4.2.2 on 2023-06-19 19:49

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocsSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_line_number", models.BooleanField(default=False)),
                (
                    "text_size",
                    models.CharField(
                        choices=[
                            ("sm", "text-sm"),
                            ("md", "text-md"),
                            ("lg", "text-lg"),
                            ("xl", "text-xl"),
                        ],
                        default="text-sm",
                        max_length=128,
                    ),
                ),
                ("blur", models.CharField(blank=True, max_length=128)),
                ("shadow", models.CharField(default="shadow", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="PostGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(blank=True, max_length=1024)),
                ("body", mdeditor.fields.MDTextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=1024)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="docme.postgroup",
                    ),
                ),
            ],
        ),
    ]
